### ISSUE TITLE
py.typed file missing

### ISSUE THREAD

**Issue by phillipuniverse** [launchdarkly/python-server-sdk#165]
**Describe the bug**
It looks like this library is fully typed but when I use mypy to lint my code I get this:

```
"ldclient": module is installed, but missing library stubs or py.typed marker
[import]
    import ldclient
    ^
```

In a python file that has:

```python
import ldclient
ldclient.client.LDClient(...)
...
```

I think the only thing that needs to happen is create a `py.typed` marker file in the `ldclient` package directory?

**To reproduce**

1. Mypy `0.942`
2. This mypy config in `pyprojec.toml`:

```toml
[tool.mypy]
plugins = [
    "pydantic.mypy",
    "sqlmypy"
]
exclude = [
    "build",
    "dist",
    ".venv",
    "venv",
    "get-poetry.py",
]
namespace_packages = true 
explicit_package_bases = true
strict = true
pretty = true
show_error_codes = true

    [[tool.mypy.overrides]]
    module = [
        "stuptools.*",
    ]
    ignore_missing_imports = true
```

Then linting with `mypy .`.

**Expected behavior**
Mypy passes

**Logs**
N/A

**SDK version**
7.4.0

**Language version, developer tools**
Python 3.7

**OS/platform**
MacOS

**Additional context**
N/A
